project:
  type: website

website:
  title: "Séamus Murphy"
  search: false
  favicon: favicon.png
  open-graph: 
    image: card.png
  page-footer:
    left: "[Source](https://github.com/seamusrobertmurphy/bio)"
  navbar:
    id: top-nav
    pinned: true
    toggle-position: right
    right:
      - talks/index.qmd
      - workshops/index.qmd
      - teaching/index.qmd
    tools:
    - icon: github
      text: GitHub
      href: https://github.com/cwickham
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/charlotte-wickham-793a011a/

brand:
  light: _brand-light.yml
  dark: _brand.yml

format:
  html:
    theme: 
      - default
      - _brand.yml